### ISSUE TITLE
Add dependabot to track dep updates

### ISSUE THREAD

**Issue by tverderesi** [PhelipeLB/Cosvesi-project#31]
I was installing the project and got a lot of outdated warnings, therefore I think the project should have dependabot integration, as it provides an easy way to keep the dependencies updated, with deployment integration it makes it super easy to see if the integration is working, as well.

**Comment by daniloab** [comment]
- [ ] follow this https://dev.to/daniloab/using-github-actions-to-improve-your-developer-experience-29n7
- [ ] create new yml file inside `.github` path
- [ ] paste the code below
```yml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'next'
      - dependency-name: 'eslint-config-next'
```
