### ISSUE TITLE
dependabot automerge workflow

### ISSUE THREAD

**Issue by daniloab** [PhelipeLB/Cosvesi-project#32]
- [ ] new yml file `automerge.yml` inside `.github/workflows`
- [ ] paste the code below
```yml
name: auto-merge

on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          command: 'squash and merge'
          target: minor
```
- [ ] create a new secret for the repo in the settings named `AUTOMERGE_TOKEN`
